name: Release Automation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y patchelf zip
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install nuitka python-telegram-bot

      - name: Extract version number
        id: extract_version
        run: |
          VERSION=$(grep VERSION_DLOADBOX bin/dloadbox-installer.sh | head -n 1 | awk -F '"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build binary with Nuitka
        run: |
          source venv/bin/activate
          mkdir -p build_output
          nuitka --standalone --onefile \
            --include-package=requests \
            --include-package=logging \
            --include-package=os \
            --include-package=telegram \
            --enable-plugin=pylint-warnings \
            --output-dir=build_output source/dloadbox-telegrambot.py
          mv build_output/dloadbox-telegrambot bin/dloadbox-telegrambot

      - name: Create dloadbox.zip
        run: |
          zip -r dloadbox.zip . -x ".git/*" ".github/*" "release_notes.md"

      - name: Create release notes
        id: generate_notes
        run: |
          echo "# Version: $VERSION" > release_notes.md
          echo "## Installation" >> release_notes.md
          echo "\`\`\`bash" >> release_notes.md
          echo "wget https://github.com/${{ github.repository }}/releases/download/$VERSION/dloadbox-installer.sh" >> release_notes.md
          echo "chmod +x dloadbox-installer.sh" >> release_notes.md
          echo "./dloadbox-installer.sh" >> release_notes.md
          echo "\`\`\`" >> release_notes.md

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body_path: ./release_notes.md
          files: |
            bin/dloadbox-installer.sh
            bin/dloadbox-telegrambot
            dloadbox.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
